name: GestroKey CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      reason:
        description: '触发原因'
        required: false
        default: '手动触发构建'

jobs:
  # 手动触发的Nuitka编译工作流
  nuitka-build:
    name: Nuitka编译
    runs-on: windows-latest
    # 仅在手动触发时运行
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt

      - name: 安装ImageMagick
        run: choco install imagemagick -y

      - name: 转换SVG到ICO
        run: |
          # 确保目标文件夹存在
          New-Item -ItemType Directory -Force -Path src/assets/images | Out-Null
          
          # 检查SVG文件是否存在
          if (-not (Test-Path -Path src/assets/images/icon.svg)) {
              Write-Error "缺少SVG图标文件: src/assets/images/icon.svg"
              exit 1
          }
          
          # 使用更新的magick命令语法
          magick src/assets/images/icon.svg -background none -resize 256x256 icon-256.png
          magick src/assets/images/icon.svg -background none -resize 128x128 icon-128.png
          magick src/assets/images/icon.svg -background none -resize 64x64 icon-64.png
          magick src/assets/images/icon.svg -background none -resize 48x48 icon-48.png
          magick src/assets/images/icon.svg -background none -resize 32x32 icon-32.png
          magick src/assets/images/icon.svg -background none -resize 16x16 icon-16.png
          
          # 合并所有PNG为一个ICO文件
          magick icon-256.png icon-128.png icon-64.png icon-48.png icon-32.png icon-16.png src/assets/images/icon.ico
          
          # 清理临时文件
          Remove-Item icon-*.png

      - name: 使用Nuitka编译
        run: |
          python -m nuitka --standalone --enable-plugin=pyqt6 --include-data-dir=src/assets=assets --windows-icon-from-ico=src/assets/images/icon.ico --output-dir=dist src/main.py

      - name: 复制必要文件
        run: |
          # 复制默认手势库、默认设置等必要文件
          if exist "src/assets" xcopy /E /I "src/assets" "dist/main.dist/assets"
          if exist "src/core" xcopy /E /I "src/core" "dist/main.dist/core"
          if exist "src/ui" xcopy /E /I "src/ui" "dist/main.dist/ui"

      - name: 创建压缩包
        run: |
          cd dist
          powershell Compress-Archive -Path main.dist -DestinationPath GestroKey-windows.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: GestroKey-windows
          path: dist/GestroKey-windows.zip
          retention-days: 7