name: Build with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka ordered-set
          # 安装你的项目依赖
          pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          python -m nuitka --standalone --mingw64 --windows-disable-console --onefile --show-progress --show-memory --plugin-enable=tk-inter --output-dir=dist src/main.py

      - name: Create release directory
        run: |
          mkdir release
          copy dist\main.exe release\app.exe
          # 如果需要包含其他文件（如配置文件、资源文件等）
          # copy config.ini release\
          # copy -Recurse assets\ release\assets\

      - name: Compress release files
        run: |
          # 使用7-Zip压缩（Windows runner自带）
          7z a -tzip release/app.zip .\release\*
          # 或者使用PowerShell压缩（不需要额外工具）
          # Compress-Archive -Path .\release\* -DestinationPath .\release\app.zip -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: release/app.zip
