name: GestroKey CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      reason:
        description: '触发原因'
        required: false
        default: '手动触发构建'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        # 如果有测试脚本，可以在这里运行
        echo "运行测试..."

  # 手动触发的Nuitka编译工作流
  nuitka-build:
    name: Nuitka编译
    runs-on: windows-latest
    # 仅在手动触发时运行
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt

      - name: 使用Nuitka编译
        run: |
          python -m nuitka --standalone --enable-plugin=pyqt6 --include-data-dir=src/assets=assets --windows-icon-from-ico=src/assets/images/icon.ico --output-dir=dist src/main.py

      - name: 复制必要文件
        run: |
          # 复制默认手势库、默认设置等必要文件
          if exist "src/assets" xcopy /E /I "src/assets" "dist/main.dist/assets"
          if exist "src/core" xcopy /E /I "src/core" "dist/main.dist/core"
          if exist "src/ui" xcopy /E /I "src/ui" "dist/main.dist/ui"

      - name: 创建压缩包
        run: |
          cd dist
          powershell Compress-Archive -Path main.dist -DestinationPath GestroKey-windows.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: GestroKey-windows
          path: dist/GestroKey-windows.zip
          retention-days: 7